### PR TITLE
v13.06

### PR DESCRIPTION
**Pull request by tswicegood**
Update all stable packages to their latest.
- [x] Add armstrong.esi
- [x] Update armstrong.core.arm_access
- [ ] Update armstrong.core.arm_content (@tswicegood)
- [x] Update armstrong.core.arm_layout (@joncotton)
- [ ] Update armstrong.core.arm_sections (@joncotton)
- [x] Update armstrong.core.arm_wells (@tswicegood)
- [ ] Update armstrong.apps.articles (@tswicegood)
- [ ] Update armstrong.apps.content (@tswicegood)
- [ ] Update armstrong.apps.images (@joncotton) --waiting for review/merge
- [ ] Update armstrong.apps.related_content (@tswicegood)
- [x] Update armstrong.hatband (@tswicegood)
- [ ] Update armstrong.cli (maybe?)

### CODE REVIEW

**Comment by joncotton** [comment]
I'm waiting on ArmLayout so I can make progress. Aside from dropping the Django pip requirement and updating TravisCI is there anything else?

**Comment by tswicegood** [comment]
@joncotton the tests should point out any issues.

**Comment by joncotton** [comment]
We should also update the readme to replace Bay Citizen with CIR and bump the copyright date to 2013.

**Comment by joncotton** [comment]
Also, given the plan to break BC in Armstrong.Dev 2.0, now is a good time to cap that package to `<2.0` in the `dev.txt` requirements file.

**Comment by tswicegood** [comment]
@joncotton are the one's you've marked off on PyPI yet?

**Comment by joncotton** [comment]
@tswicegood nope. They are open PRs for review. The check just means "I'm done with it". The next step is merge and version bump.

**Comment by tswicegood** [comment]
Ahh -- I've been using those as they're upgraded, released, and their dependency is updated in the main armstrong package.

**Comment by joncotton** [comment]
I actually wondered if that was the case before I checked my own boxes. (I'll uncheck and make a margin note.)

So you'll see a PR from me against your ArmAccess branch. Guess I made that too late. I'm content to wait for review (it'll be easy so who cares), but I am happy to merge, bump, push. Whatever you or @Jbonnett like. I don't have the PyPi credentials though.

**Comment by joncotton** [comment]
@tswicegood congrats on the official new job! Feel free to pass any or all of these packaging and update tasks to me. Let me know the work you've done already though (or link me to your branches) so I don't duplicate effort. Maybe we move this release to **13.08** and keep **13.09** for new features.

Let's coordinate and then update the status on the [mailing list thread](https://groups.google.com/d/msg/armstrongcms/sB1EaUEfrws/GlgHnMWrpJEJ).

**Pull request closed without merging**
